#server.port=8128
#spring.data.mongodb.uri=mongodb+srv://hantoniovr_db_user:anto1234@mongohavr.qz7sphg.mongodb.net/saber
spring.application.name=saberpro
server.port=${PORT:8080}
spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.database=saber
